import { LanguageCode, Translation } from './types';

export const TRANSLATIONS: Record<LanguageCode, Translation> = {
  ar: {
    title: "AutoDiag AI – Smart Car Diagnosis BOUHLALA",
    subtitle: "أداة تشخيص أعطال السيارات الذكية المتقدمة",
    inputSection: "بيانات المركبة والعطل",
    make: "الشركة المصنعة (مثال: تويوتا)",
    model: "الموديل (مثال: كامري)",
    year: "سنة الصنع",
    symptoms: "وصف العطل أو الأصوات المسموعة",
    symptomsPlaceholder: "اشرح المشكلة بالتفصيل... (مثال: صوت طقطقة عند الانعطاف لليمين)",
    analyzeButton: "ابدأ التشخيص الذكي",
    analyzing: "جاري تحليل البيانات عبر الذكاء الاصطناعي...",
    resultsTitle: "تقرير التشخيص",
    possibleCauses: "الأسباب المحتملة",
    solutions: "الحلول المقترحة",
    severity: "مستوى الخطورة",
    warning: "تنبيه هام",
    safetyTip: "نصيحة سلامة",
    visitMechanic: "يوصى بزيارة مختص لإجراء فحص دقيق.",
    footer: "تم تصميم الأداة M-BOUHLALA",
    error: "حدث خطأ أثناء الاتصال بالخدمة. يرجى المحاولة مرة أخرى.",
    reset: "تشخيص جديد"
  },
  en: {
    title: "AutoDiag AI – Smart Car Diagnosis BOUHLALA",
    subtitle: "Advanced AI-Powered Car Diagnostic Tool",
    inputSection: "Vehicle & Symptom Details",
    make: "Manufacturer (e.g., Toyota)",
    model: "Model (e.g., Camry)",
    year: "Year",
    symptoms: "Symptom Description",
    symptomsPlaceholder: "Describe the issue in detail... (e.g., clicking noise when turning right)",
    analyzeButton: "Start AI Diagnosis",
    analyzing: "Analyzing data via AI Engine...",
    resultsTitle: "Diagnosis Report",
    possibleCauses: "Possible Causes",
    solutions: "Suggested Solutions",
    severity: "Severity Level",
    warning: "Important Warning",
    safetyTip: "Safety Tip",
    visitMechanic: "It is recommended to visit a specialist for a precise inspection.",
    footer: "Designed by M-BOUHLALA",
    error: "An error occurred while connecting to the service. Please try again.",
    reset: "New Diagnosis"
  },
  fr: {
    title: "AutoDiag AI – Smart Car Diagnosis BOUHLALA",
    subtitle: "Outil de diagnostic automobile avancé par IA",
    inputSection: "Détails du véhicule et symptômes",
    make: "Fabricant (ex: Renault)",
    model: "Modèle (ex: Clio)",
    year: "Année",
    symptoms: "Description du symptôme",
    symptomsPlaceholder: "Décrivez le problème en détail... (ex: bruit de claquement en tournant à droite)",
    analyzeButton: "Lancer le diagnostic IA",
    analyzing: "Analyse des données par le moteur IA...",
    resultsTitle: "Rapport de diagnostic",
    possibleCauses: "Causes possibles",
    solutions: "Solutions suggérées",
    severity: "Niveau de gravité",
    warning: "Avertissement important",
    safetyTip: "Conseil de sécurité",
    visitMechanic: "Il est recommandé de consulter un spécialiste pour une inspection précise.",
    footer: "Conçu par M-BOUHLALA",
    error: "Une erreur s'est produite lors de la connexion au service. Veuillez réessayer.",
    reset: "Nouveau diagnostic"
  },
  de: {
    title: "AutoDiag AI – Smart Car Diagnosis BOUHLALA",
    subtitle: "Fortschrittliches KI-gestütztes Autodiagnosetool",
    inputSection: "Fahrzeug- & Symptomdetails",
    make: "Hersteller (z.B. BMW)",
    model: "Modell (z.B. X5)",
    year: "Baujahr",
    symptoms: "Problembeschreibung",
    symptomsPlaceholder: "Beschreiben Sie das Problem im Detail...",
    analyzeButton: "KI-Diagnose starten",
    analyzing: "Daten werden analysiert...",
    resultsTitle: "Diagnosebericht",
    possibleCauses: "Mögliche Ursachen",
    solutions: "Vorgeschlagene Lösungen",
    severity: "Schweregrad",
    warning: "Wichtige Warnung",
    safetyTip: "Sicherheitshinweis",
    visitMechanic: "Es wird empfohlen, einen Spezialisten für eine genaue Inspektion aufzusuchen.",
    footer: "Entworfen von M-BOUHLALA",
    error: "Ein Fehler ist aufgetreten.",
    reset: "Neue Diagnose"
  },
  es: {
    title: "AutoDiag AI – Smart Car Diagnosis BOUHLALA",
    subtitle: "Herramienta de diagnóstico de automóviles con IA",
    inputSection: "Detalles del vehículo y síntomas",
    make: "Fabricante (ej. Ford)",
    model: "Modelo (ej. Focus)",
    year: "Año",
    symptoms: "Descripción del síntoma",
    symptomsPlaceholder: "Describa el problema en detalle...",
    analyzeButton: "Iniciar diagnóstico IA",
    analyzing: "Analizando datos...",
    resultsTitle: "Informe de diagnóstico",
    possibleCauses: "Causas posibles",
    solutions: "Soluciones sugeridas",
    severity: "Nivel de gravedad",
    warning: "Advertencia importante",
    safetyTip: "Consejo de seguridad",
    visitMechanic: "Se recomienda visitar a un especialista para una inspección precisa.",
    footer: "Diseñado por M-BOUHLALA",
    error: "Ocurrió un error.",
    reset: "Nuevo diagnóstico"
  }
};
